### ISSUE TITLE
Shape mismatch in train.py

### ISSUE THREAD

**Issue by nightrangerdotcom** [dvl-tum/group_loss#7]
Hi! 
Running `python train.py` on the cub dataset, I'm dealing with this problem:

`
RuntimeError: output with shape [1, 227, 227] doesn't match the broadcast shape [3, 227, 227]
`

It occurs in these lines: 

` for x, Y in dl_tr:`
`Y = Y.to(device)`
`opt.zero_grad()`

Where's the problem and how can I solve it?

**Comment by TheRevanchist** [comment]
My belief is that there might be one (or more) images in CUB which have depth shape 1 instead of 3. The easiest solution would be to find those images (just write a script which simply opens the images and checks their size, and then finds those with size different to XxYx3) and rewrite them by simply copying the z channel 3 times.

**Comment by nightrangerdotcom** [comment]
Thank you, it actually worked
